_target_: src.models.coco_module.COCOLitModule
lr: 0.001
weight_decay: 0.0005

net:
  _target_: src.models.component.yolov5.models.yolo.Model
  cfg: 'src/models/component/yolov5/models/yolov5s.yaml'


